version: '3'
services:
  nodejs-app:
    container_name: auth-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    # depends_on:
    #   - mongo
    networks:
      - app-network

  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   volumes:
  #     - mongodb-data:/data/db
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: